FROM selenium/node-firefox

USER root
#=========
# Firefox
#=========
RUN apt-get update && apt-get install -y firefox wget

RUN apt-get update && apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common libffi-dev xvfb
RUN apt-add-repository ppa:brightbox/ruby-ng && apt-get update
RUN apt-get install -y ruby2.5-dev ruby2.5
RUN mkdir /app
WORKDIR app

ADD Gemfile Gemfile.lock /app/
RUN gem update --system
RUN gem install bundler && bundle install
ADD . /app

# Install Xvfb init script
ENV DISPLAY :99

ADD docker/test/run.sh /run.sh
RUN chmod -R a+rwx /app
RUN chmod a+x /run.sh

CMD /run.sh
USER seluser